version: '3.7'

services:
    api:
        container_name: org-tracker-api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /tmp/logs:/opt/apache-tomcat-aclogs/
        ports:
            - '5000:3000'
        environment:
            - PORT=3000
